spring:
    profiles:
        active: dev   
---
spring:
    profiles:  dev
    application: 
        name: springcloud-aiguigu-dev
---
spring:
    profiles:  test
    application: 
        name: springcloud-aiguigu-test
# 请保存为utf-8格式        